config/routes.rb
#encoding: utf-8;
Giftr3::Application.routes.draw do
  
  root :to => 'main#index'
  match 'admin' => 'admin/products#index', :as => :admin
  mount Lk::Engine => "/lk", :as => :lk_engine
  mount Auth::Engine => "/auth", :as => :auth_engine

  resources :main, :only => [:index] do
    get :change_scrollable, :on => :collection
  end
  resources :orders, :only => [:create, :index, :show], :controller => :user_orders do
    get :complete, :on => :collection
  end
 
  namespace :api do
    resources :categories, :only => [:index, :show] do
      collection do 
        get :thematics
        get :analogs
        get :virtuals        
      end
    end
    resources :products, :only => [:index, :show] do
      collection do 
        get :novelty
        get :sale
        get :lk
      end
    end
    resources :search, :only => [:index]
    resources :orders, :only => [:create]
    
  end
   
  namespace :admin do
    resources :firms do
      member do
        post :add_image
        delete :remove_image
      end 
    end   
    resources :accounts do   
      member do
          put :activate
        end
      end
    resources :banners do 
      
    end
    resources :main
    resources :news
    resources :categories  do    
      member do
        get :show_products_list
        post :change_category_products
        post :move
        post :add_image
        delete :remove_image
        post :change_sort
        get :child_items
      end    
      collection do
        get :catalog
        get :thematic
        get :analogs
        get :virtuals
      end
    end
    resources :contents
    resources :content_categories
    resources :content_images, :only => [:index, :create, :destroy] do
      collection do 
        get :galery
      end
    end
    resources :manufactors
    resources :suppliers do 
      resources :stores, :except => [:index, :show]
      member do 
        get :truncate_products
      end
    end
    resources :images do
      collection do
        get :all
      end
    end
    resources :currency_values, :only => [:index, :create, :destroy] do
      get :cbrf_tax, :on => :collection
    end
    resources :products do    
      member do
        put :activate
        get :inline_property_values
        post :update_inline
      end
      post :group_ops, :on => :collection  
      post :fields_settings, :on => :collection
      resources :images do
        member do
          delete :remove
          get :set_main
        end
      end
    end
    resources :properties do  
      resources :values, :controller => "property_values" do 
        member do
          post :join
        end
      end
      member do
        get :load_filter_values
      end
    end
    resources :data_changes do
      collection do
        post :import
        get :get_status
      end    
      member do 
        get :stop
      end
    end
    resources :export_data do
      collection do
        post :export
        get :permalinks
      end        
    end
    resources :foreign_access
    resources :services
    resources :roles
  end
end

app/controllers/admin/content_categories_controller.rb
#encoding: utf-8;
class Admin::ContentCategoriesController < Admin::BaseController
  access_control do
     allow :admin, :admin_content
  end
  
  def index
    @content_categories = ContentCategory.all
  end

  def new
    @content_category = ContentCategory.new
  end
  
  def create
    @content_category = ContentCategory.new(params[:content_category])
    if @content_category.save
      flash[:notice] = "Категория создана"
      redirect_to edit_admin_content_category_path(@content_category)
    else
      render :new
    end
  end
  

  def edit
    @content_category = ContentCategory.find_by_permalink(params[:id])
  end

  def update
    @content_category = ContentCategory.find_by_permalink(params[:id])
    if @content_category.update_attributes(params[:content_category])
      flash[:notice] = "Категория изменена"
      redirect_to edit_admin_content_category_path(@content_category)
    else
      render :edit
    end
  end  
  
  def destroy
    @content_category = ContentCategory.find_by_permalink(params[:id])
    if @content_category.contents.empty?
      @content_category.destroy
      flash[:notice] = "Категория удалена"
    else
      flash[:alert] = "Не могу удалить категорию. Имеются записи."
    end
    redirect_to admin_content_categories_path
  end  

end

app/helpers/admin/content_categories_helper.rb
module Admin::ContentCategoriesHelper
end

app/views/admin/content_categories/_content_category.html.erb
<%= form_for [:admin, @content_category], :html => {:class=> "one_line_form"} do |f| %>
   <%= render :partial => 'shared/error_messages', :locals => {:target => @content_category} %>
  <div class="b-formfield-div">
    <%= f.label :name, 'Название категории*' %>
    <%= f.text_field :name %>
  </div>
  <div class="b-formfield-div">
    <%= f.label :permalink, 'Permalink' %>
    <%= f.text_field :permalink %>
  </div>
  <div class="b-formfield-div">
    <%= f.submit "Сохранить" %>
  </div>  
  <% end -%>

app/views/admin/content_categories/edit.html.erb
<%= render :partial => 'admin/shared/sub_menu_content' %>
<% title "Редактирование категории" -%>
<div class="grid_8">
<%= render :partial => "content_category" %>
</div>
<div class="clear"></div>

<div class="grid_16">
<%= link_to 'Назад с списку категорий',  admin_content_categories_path %>
</div>

app/views/admin/content_categories/index.html.erb
<%= render :partial => 'admin/shared/sub_menu_content' %>
<% title "Категории контента" -%>

<div class="b-command-menu">
<%= link_to 'Новая категория', new_admin_content_category_path  %>
</div>

<table>
<tr>
  <th></th>
  <th>Название</th>
  <th>Дата создания</th>
  <th></th>
</tr>
<% @content_categories.each do |item| -%>
  <tr>
    <td><%= link_to image_tag('edit.png'), edit_admin_content_category_path(item) %></td>
    <td><%= item.name %></td>
    <td><%= I18n.l(item.created_at, :format =>:long) %></td>
    <td><%= link_to image_tag('bin.png'), admin_content_category_path(item), :method => :delete, :confirm => "Вы уверены?"%></td>
  </tr>  
<% end -%>
</table>

app/views/admin/content_categories/new.html.erb
<%= render :partial => 'admin/shared/sub_menu_content' %>
<% title "Новая категория" -%>
<div class="grid_8">
<%= render :partial => "content_category" %>
</div>
<div class="clear"></div>

<div class="grid_16">
<%= link_to 'Назад с списку категорий',  admin_content_categories_path %>
</div>