config/routes.rb
#encoding: utf-8;
Giftr3::Application.routes.draw do
  
  root :to => 'main#index'
  match 'admin' => 'admin/products#index', :as => :admin
  mount Lk::Engine => "/lk", :as => :lk_engine
  mount Auth::Engine => "/auth", :as => :auth_engine

  resources :main, :only => [:index] do
    get :change_scrollable, :on => :collection
  end
  resources :orders, :only => [:create, :index, :show], :controller => :user_orders do
    get :complete, :on => :collection
  end
 
  namespace :api do
    resources :categories, :only => [:index, :show] do
      collection do 
        get :thematics
        get :analogs
        get :virtuals        
      end
    end
    resources :products, :only => [:index, :show] do
      collection do 
        get :novelty
        get :sale
        get :lk
      end
    end
    resources :search, :only => [:index]
    resources :orders, :only => [:create]
    
  end
   
  namespace :admin do
    resources :firms do
      member do
        post :add_image
        delete :remove_image
      end 
    end   
    resources :accounts do   
      member do
          put :activate
        end
      end
    resources :banners do 
      
    end
    resources :main
    resources :news
    resources :categories  do    
      member do
        get :show_products_list
        post :change_category_products
        post :move
        post :add_image
        delete :remove_image
        post :change_sort
        get :child_items
      end    
      collection do
        get :catalog
        get :thematic
        get :analogs
        get :virtuals
      end
    end
    resources :contents
    resources :content_categories
    resources :content_images, :only => [:index, :create, :destroy] do
      collection do 
        get :galery
      end
    end
    resources :manufactors
    resources :suppliers do 
      resources :stores, :except => [:index, :show]
      member do 
        get :truncate_products
      end
    end
    resources :images do
      collection do
        get :all
      end
    end
    resources :currency_values, :only => [:index, :create, :destroy] do
      get :cbrf_tax, :on => :collection
    end
    resources :products do    
      member do
        put :activate
        get :inline_property_values
        post :update_inline
      end
      post :group_ops, :on => :collection  
      post :fields_settings, :on => :collection
      resources :images do
        member do
          delete :remove
          get :set_main
        end
      end
    end
    resources :properties do  
      resources :values, :controller => "property_values" do 
        member do
          post :join
        end
      end
      member do
        get :load_filter_values
      end
    end
    resources :data_changes do
      collection do
        post :import
        get :get_status
      end    
      member do 
        get :stop
      end
    end
    resources :export_data do
      collection do
        post :export
        get :permalinks
      end        
    end
    resources :foreign_access
    resources :services
    resources :roles
  end
end

app/controllers/admin/foreign_access_controller.rb
#encoding: utf-8;
class Admin::ForeignAccessController < Admin::BaseController
  access_control do
     allow :admin, :admin_users
  end

  before_filter :find_firms, :only => [:new, :create, :update, :edit]
  
  def index
    @catalog_clients = ForeignAccess.all
  end

  def new
    @access_item =ForeignAccess.new
  end

  def create
      @access_item =ForeignAccess.new(params[:access_item])
      if @access_item.save
        flash[:notice] = "Запись создана"
        redirect_to admin_foreign_access_index_path
      else
        render 'new'
      end  
  end

  def edit
    @access_item= ForeignAccess.find(params[:id])    
  end

  def update
    @access_item = ForeignAccess.find(params[:id])
    if @access_item.update_attributes  params[:access_item]
      flash[:notice] = "Запись изменена"
      redirect_to admin_foreign_access_index_path
    else 
      render 'edit'  
    end
  end

  def destroy
    access_item = ForeignAccess.find(params[:id])
    access_item.destroy
    redirect_to admin_foreign_access_index_path
  end
  
  private
  
  def find_firms
    @firms = Firm.order(:short_name)
  end
  
end

app/views/admin/foreign_access/_foreign_access.erb
<div>
  <%= render :partial => 'shared/error_messages', :locals => {:target => @access_item} %>    
</div>

<div class="b-formfield-div">
  <%= f.label :firm_id, 'Фирма' %>
  <%= f.select :firm_id, options_from_collection_for_select(@firms, :id, :short_name, @access_item.firm_id), { :include_blank => true } %>
</div>


<div class="b-formfield-div">
  <%= f.label :name, 'Название доступа' %>
  <%= f.text_field :name %>
</div>
<div class="b-formfield-div">
  <%= f.label :ip_addr, 'IP адрес' %>
  <%= f.text_field :ip_addr %>
</div>
<div class="b-formfield-div">
  <%= f.label :param_key, 'Ключ' %>
  <%= f.text_field :param_key %>
</div>
<div class="b-formfield-div">
  <%= f.label :accepted_from, 'Начало действия доступа' %>
  <%= f.text_field :accepted_from %>
</div>
<div class="b-formfield-div">
  <%= f.label :accepted_to, 'Окончание действия доступа' %>
  <%= f.text_field :accepted_to %>
</div>
<div class="b-formfield-div">
  <%= f.submit "Сохранить" %>
</div>

app/views/admin/foreign_access/edit.erb
<% title 'Настройка доступа к каталогу' %>

<%= form_for :access_item, :url => admin_foreign_access_path(@access_item),  :html => {:method=>:put, :class => 'one_line_form'}  do |f|%>
<%= render :partial => "foreign_access", :locals => {:f => f} %>
<%  end %>
<div class="clr"></div>

<%= link_to 'Назад к списку', admin_foreign_access_path %>

app/views/admin/foreign_access/index.erb
<%= render :partial => 'admin/shared/sub_menu_users' %>
<%title 'Доступ к удаленному каталогу'  %>

<div class='b-command-menu'>
[<%= link_to 'Предоставить доступ', new_admin_foreign_access_path %>]
</div>

  <div id='collection_items'>
    <table>
    <tr>
      <th></th>
      <th>Фирма</th>
      <th>Название</th>
      <th>IP</th>
      <th>Ключ</th>      
      <th>Доступ с</th>      
      <th>Доступ по</th>
      <th></th>      
    </tr>
    <% @catalog_clients.each do |cl| -%>
      <tr>
        <td><%= link_to image_tag("edit.png"), edit_admin_foreign_access_path(cl) %></td>
        <td><%= cl.firm.short_name if cl.firm %></td>
        <td><%= cl.name %></td>
        <td><%= cl.ip_addr %></td>
        <td><%= cl.param_key %></td>
        <td><%= cl.accepted_from %></td>
        <td><%= cl.accepted_to %></td>        
        <td><%= link_to image_tag("bin.png"), admin_foreign_access_path(cl), :method=>:delete, :confirm=>"Удалить?"  %></td>
      </tr>
    <% end -%>
    </table>
  </div>

app/views/admin/foreign_access/new.erb
<% title 'Предоставление доступа к каталогу' %>
<%= form_for :access_item, :url => admin_foreign_access_index_path, :html => {:class => 'one_line_form'}  do |f|%>
<%= render :partial => "foreign_access", :locals => {:f => f} %>
<%  end %>
<div class="clr"></div>
<%= link_to 'Назад к списку', admin_foreign_access_index_path %>