config/routes.rb
#encoding: utf-8;
Giftr3::Application.routes.draw do
  
  root :to => 'main#index'
  match 'admin' => 'admin/products#index', :as => :admin
  mount Lk::Engine => "/lk", :as => :lk_engine
  mount Auth::Engine => "/auth", :as => :auth_engine

  resources :main, :only => [:index] do
    get :change_scrollable, :on => :collection
  end
  resources :orders, :only => [:create, :index, :show], :controller => :user_orders do
    get :complete, :on => :collection
  end
 
  namespace :api do
    resources :categories, :only => [:index, :show] do
      collection do 
        get :thematics
        get :analogs
        get :virtuals        
      end
    end
    resources :products, :only => [:index, :show] do
      collection do 
        get :novelty
        get :sale
        get :lk
      end
    end
    resources :search, :only => [:index]
    resources :orders, :only => [:create]
    
  end
   
  namespace :admin do
    resources :firms do
      member do
        post :add_image
        delete :remove_image
      end 
    end   
    resources :accounts do   
      member do
          put :activate
        end
      end
    resources :banners do 
      
    end
    resources :main
    resources :news
    resources :categories  do    
      member do
        get :show_products_list
        post :change_category_products
        post :move
        post :add_image
        delete :remove_image
        post :change_sort
        get :child_items
      end    
      collection do
        get :catalog
        get :thematic
        get :analogs
        get :virtuals
      end
    end
    resources :contents
    resources :content_categories
    resources :content_images, :only => [:index, :create, :destroy] do
      collection do 
        get :galery
      end
    end
    resources :manufactors
    resources :suppliers do 
      resources :stores, :except => [:index, :show]
      member do 
        get :truncate_products
      end
    end
    resources :images do
      collection do
        get :all
      end
    end
    resources :currency_values, :only => [:index, :create, :destroy] do
      get :cbrf_tax, :on => :collection
    end
    resources :products do    
      member do
        put :activate
        get :inline_property_values
        post :update_inline
      end
      post :group_ops, :on => :collection  
      post :fields_settings, :on => :collection
      resources :images do
        member do
          delete :remove
          get :set_main
        end
      end
    end
    resources :properties do  
      resources :values, :controller => "property_values" do 
        member do
          post :join
        end
      end
      member do
        get :load_filter_values
      end
    end
    resources :data_changes do
      collection do
        post :import
        get :get_status
      end    
      member do 
        get :stop
      end
    end
    resources :export_data do
      collection do
        post :export
        get :permalinks
      end        
    end
    resources :foreign_access
    resources :services
    resources :roles
  end
end

app/controllers/user_orders_controller.rb
#encoding: utf-8;
class UserOrdersController < ApplicationController
#  layout 'lk'
  before_filter :authenticate_user!
  access_control do
     allow :simple_user
  end

  def index
      @orders = current_user.lk_orders.order("created_at desc")     
  end
  
  def show
    #юзер не должен увидеть чужой заказ, просто поменяв id
    if current_user.lk_orders.exists?(params[:id])
      @order = LkOrder.find(params[:id])
    else
      not_found("Заказ не найден!")
    end
  end
  
    def create
      @lk_order = LkOrder.new(params[:lk_order])
      @lk_order.firm_id = params.invert["Отправить заказ"].to_i
      @lk_order.attributes = {:user => current_user, :user_name => current_user.fio ? current_user.fio : current_user.username, 
                                  :user_email => current_user.email, :user_phone => current_user.phone, :is_remote => true} 
      if @lk_order.save 
        @cart = find_cart
        @cart.items.each do |cart_item|
        @lk_order.lk_order_items.create({:product => cart_item.product, :quantity => cart_item.quantity, :price => cart_item.start_price})
        @cart.items.clear
      end
      FirmMailer.new_user_order_notification(current_user,@lk_order ).deliver if @lk_order.firm && @lk_order.firm.email.present?
      UserMailer.new_order_notification(current_user, @lk_order).deliver if  current_user.active?  && current_user.email.present? 
      redirect_to complete_orders_path, :flash => {:order_id => @lk_order.id}
    else  
      redirect_to cart_index_path, :alert => "Ошибка при оформлении заказа"
    end
    #sending message to user and company
  end
  
  def complete
    @lk_order = LkOrder.find(flash[:order_id])
    render 'complete'
  end    
end

app/views/user_orders/complete.html.erb
<% page_title "Спасибо за заказ!" -%>

<h1>Спасибо за заказ!</h1>

<p>Ваш заказ под номером <strong><%= @lk_order.id %></strong> отправлен на обработку в компанию <strong><%= @lk_order.firm.short_name %></strong>.</p>
<div class="spacer"></div>
<p>В ближайшее время с Вами свяжется менеджер компании для уточнения деталей заказа</p>

<div class="spacer"></div>
  <p>Отслеживать состояние обработки Вашего заказа Вы можете в <%= link_to "Личном кабинете", orders_path %></p>

app/views/user_orders/index.html.erb
<% page_title "Ваши заказы" -%>
<h2>Список заказов</h2>

<table width="100%">
<tr>
  <th></th>
  <th>№ заказа</th>
  <th>Компания</th>
  <th>Статус</th>
  <th>Сумма</th>
</tr>
<% @orders.each do |item| -%>
  <tr>
    <td><%= link_to image_tag('edit.png'), order_path(item) %></td>
    <td><%= item.id  %></td>
    <td><%= item.firm.name if item.firm %></td>
    <td><%= item.status %></td>
    <td><%= price_ru_label item.sum %></td>
  </tr>
<% end -%>
</table>

app/views/user_orders/show.html.erb
<% page_title "Заказ № #{@order.id}" -%>
<h2>Заказ № <%= @order.id %></h2>

<p>Дата создания: <%= I18n.l(@order.created_at, :format => :long) %></p>

<p>Текущий статус: <%= @order.status %></p>

<div class="spacer"></div>

<h3>Перечень позиций:</h3>

<table>
    <th>Изображение</th>
    <th>Артикул</th>
    <th>Наименование</th>
    <th>Цена за шт</th>
    <th>Кол-во</th>
    <th>Сумма</th>
   <% @order.lk_order_items.each do |item| -%>
     <tr>
      <td align="center"><%= image_tag(item.product && item.product.picture ? item.product.picture.url(:thumb) : "default_image.jpg") %></td>
      <td><%= article(item.product) %></td>
      <td><%= item.product.short_name %></td>
      <td><%= price_ru_label item.price %></td>
      <td><%= item.quantity %></td>
      <td><%= price_ru_label item.price * item.quantity %></td>
    </tr>
   <% end -%>
</table>