config/routes.rb
#encoding: utf-8;
Giftr3::Application.routes.draw do
  
  root :to => 'main#index'
  match 'admin' => 'admin/products#index', :as => :admin
  mount Lk::Engine => "/lk", :as => :lk_engine
  mount Auth::Engine => "/auth", :as => :auth_engine

  resources :main, :only => [:index] do
    get :change_scrollable, :on => :collection
  end
  resources :orders, :only => [:create, :index, :show], :controller => :user_orders do
    get :complete, :on => :collection
  end
 
  namespace :api do
    resources :categories, :only => [:index, :show] do
      collection do 
        get :thematics
        get :analogs
        get :virtuals        
      end
    end
    resources :products, :only => [:index, :show] do
      collection do 
        get :novelty
        get :sale
        get :lk
      end
    end
    resources :search, :only => [:index]
    resources :orders, :only => [:create]
    
  end
   
  namespace :admin do
    resources :firms do
      member do
        post :add_image
        delete :remove_image
      end 
    end   
    resources :accounts do   
      member do
          put :activate
        end
      end
    resources :banners do 
      
    end
    resources :main
    resources :news
    resources :categories  do    
      member do
        get :show_products_list
        post :change_category_products
        post :move
        post :add_image
        delete :remove_image
        post :change_sort
        get :child_items
      end    
      collection do
        get :catalog
        get :thematic
        get :analogs
        get :virtuals
      end
    end
    resources :contents
    resources :content_categories
    resources :content_images, :only => [:index, :create, :destroy] do
      collection do 
        get :galery
      end
    end
    resources :manufactors
    resources :suppliers do 
      resources :stores, :except => [:index, :show]
      member do 
        get :truncate_products
      end
    end
    resources :images do
      collection do
        get :all
      end
    end
    resources :currency_values, :only => [:index, :create, :destroy] do
      get :cbrf_tax, :on => :collection
    end
    resources :products do    
      member do
        put :activate
        get :inline_property_values
        post :update_inline
      end
      post :group_ops, :on => :collection  
      post :fields_settings, :on => :collection
      resources :images do
        member do
          delete :remove
          get :set_main
        end
      end
    end
    resources :properties do  
      resources :values, :controller => "property_values" do 
        member do
          post :join
        end
      end
      member do
        get :load_filter_values
      end
    end
    resources :data_changes do
      collection do
        post :import
        get :get_status
      end    
      member do 
        get :stop
      end
    end
    resources :export_data do
      collection do
        post :export
        get :permalinks
      end        
    end
    resources :foreign_access
    resources :services
    resources :roles
  end
end

app/controllers/admin/images_controller.rb
#encoding: utf-8;
class Admin::ImagesController < Admin::BaseController

  access_control do
     allow :admin, :admin_catalog
  end
    
  def all
    params[:page] ||=1
    @images= Image.paginate(:page=>params[:page])
  end
  
  def index
    if params[:product_id]
      @product= Product.find_by_permalink(params[:product_id])
    end
  end

  def create
    product = Product.find_by_permalink(params[:product_id])
    if AttachImage.create(:attachable => product, :image => Image.create(params[:image]))
      flash[:notice] = "Изображение успешно сохранено"
    else
      flash[:alert] = "Ошибка добавленя изображения!"
    end
    redirect_to admin_product_images_path(params[:product_id])
  end


  def destroy
     image=Image.find(params[:id])
     flash[:notice] = "Изображение удалено" if image.destroy     
     redirect_to all_admin_images_path(params[:product_id])
  end
  
  def remove
    product = Product.find_by_permalink(params[:product_id])
    #flash[:notice] = "Изображение исключено из товара, но осталось на сервере" if product.images.delete(Image.find(params[:id]))
    image = Image.find(params[:id])
   flash[:notice] = "Изображение отвязано от товара" if product.images.delete(image) 
    redirect_to admin_product_images_path(params[:product_id])
  end
  
  def set_main
    @product = Product.find(params[:product_id])
    attach_image = @product.attach_images.find_by_image_id(params[:id])    
    @product.touch if attach_image.toggle! :main_img    
    respond_to do |format|
      format.js {render 'reload_images'}
      format.html {redirect_to admin_product_images_path(@product)}
    end
  end
  
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/views/admin/images/_product_image_list.erb
<table>
  <tr>
    <th>Изображение</th>
    <th>Имя файла</th>
    <th>Размер</th>
    <th>Основное</th>
    <th>Дт. создания</th>
    <th></th>
  </tr>
  <% @product.attach_images.each do |item| -%>
   <tr>
    	<td>
    	  <%= image_tag item.image.picture.url(:thumb) %>

    	</td>
    	<td>
    	  <%= item.image.picture_file_name %> <br />
     	  <%= link_to 'оригинал', "#", :onclick =>"window.open('#{item.image.picture.url}','new_window_name','height=300,width=300')" %>
    	</td>
    	<td>
    	  <%= number_to_human_size(item.image.picture_file_size) %>
    	</td>
    	<td><%= link_to checked_box_image(item.main_img), set_main_admin_product_image_path(@product.id, item.image_id), :remote => true  %></td>
    	<td>
    	  <%= item.image.created_at.to_s %>
    	</td>
    	<td><%= link_to image_tag('bin.png'), remove_admin_product_image_path(@product,item.image_id), :method => :delete, :confirm => 'Изображение будет отвязано от товараю Вы уверены?', :title=>'Отвязать изображение от товара'  %></td>
    </tr>
  <% end -%>

</table>

app/views/admin/images/_upload_image.erb
<fieldset>
<legend>Загрузить изображение из файла</legend>
 <%= form_for :image,  :url => upload_image, :html => { :multipart => true } do |form| %>
    <%= form.file_field defined?(paperclip_name) ? paperclip_name : :picture %>
    <%= form.submit "Ок" %>
  <% end %>
</fieldset>

app/views/admin/images/all.html.erb
<%title 'Все изображения'  %>
<div class="g-left">
  <div>
<table>
  <tr>
    <th>Код</th>
    <th>Изображение</th>
    <th>Имя файла</th>
    <th>Размер</th>
     <th>Дт. создания</th>     
     <th>Ссылок</th>
     <th></th>
  </tr>
  <% @images.each do |item| -%>
   <tr>
      <td><%= item.id %></td>
    	<td>
    	  <%= image_tag item.picture.url(:thumb) %>

    	</td>
    	<td>
    	  <%= item.picture_file_name %> <br />
     	  <%= link_to 'оригинал', item.picture.url, :popup => ['new_window_name', 'height=300,width=300']  %>
    	</td>
    	<td>
    	  <%= number_to_human_size(item.picture_file_size) %>
    	</td>
    	<td>
    	  <%= item.created_at.to_s %>
    	</td>
      <td>
        <%= item.attach_images.count %>
      </td>      
    	<td><%= link_to image_tag('bin.png'), admin_image_path(item), :method => :delete, :confirm => 'Изображение будет удалено безвозвратно! Вы уверены?'  %></td>
    </tr>
  <% end -%>
  

</table>
  </div>
</div>

<div class="clr"></div>

<%= will_paginate @images %>

app/views/admin/images/index.erb
<%= render 'admin/shared/sub_menu_product2' %>

<%title 'Изображения товара'  %>

  <div class="b-uploadfile">
  <%= render :partial => 'upload_image', :object => admin_product_images_path(@product) %>
  </div>


<div class="clear"></div>
  <div>
    <h3>Список изображений </h3>
    <div id="product_image_list">
     <%= render :partial => "product_image_list" %>
     </div>
  </div>

<div class="clr"></div>

app/views/admin/images/reload_images.js.erb
$('#product_image_list').html("<%= escape_javascript render(:partial => 'product_image_list') %>");